### ISSUE TITLE
Are you going to distribute version 6?

### ISSUE THREAD

**Issue by chillenb** [conda-forge/libcint-feedstock#28]
### Comment:

Libcint 6 has faster range-separated integrals. It'd be nice if it were available on conda-forge!

**Comment by BastianZim** [comment]
Hi @chillenb, sorry, completely forgot about this but I saw you opened a PR, thanks! If you want, feel free to add yourself as a maintainer in that PR as well.

**Comment by chillenb** [comment]
Thanks for your help! I've added myself as a maintainer in a new commit on #29 :)
That automatically restarted Travis. Hopefully it'll work this time!

**Comment by BastianZim** [comment]
Great!
Yes, unfortunately, Travis often has to be restarted multiple times before it works...
